This package 'covBM' is a reworked version of a package submitted under the name 'corBM' earlier in the year (19/02/2015). The previous package was not compatible with CRAN policies and so was rejected. However, the new package 'covBM' has been restructured to avoid the problems present in the initial submission to CRAN.

The 'nlme' package is listed in the DESCRIPTION under 'Depends:' rather than 'Imports:' because functions from the 'nlme' package are required to extract useful summaries of objects generated by the 'covBM' package.

## Test environments
* ubuntu 12.04 (on travis-ci), R 3.2.2
* win-builder (devel and release)

## R CMD check results
There were no ERRORs or WARNINGs. 

The only NOTE was 'New submission'.
